/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_gpio_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_TIMER_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_RCC_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_USART_driver.h"


#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include "../Src/HAL/LCD/LCD_Interface.h"
#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"

#include "../Src/HAL/includes/MPU6050.h"


#include "../Src/HAL/Stepper/Stepper.h"


#include "../Src/HAL/includes/DC_Motor.h"

#define TARGET_DISTANCE_MIN 2
#define TARGET_DISTANCE_MAX




extern float AccErrorX, AccErrorY;
extern int GyroErrorX, GyroErrorY, GyroErrorZ;


char buffer[5];
char yaw_str[5];
char pitch_str[5];
char roll_str[5];






void Clock_Init()
{
	MCAL_RCC_CLK_Init(HSE_CLK, RCC_CLK_72M);  // is a must due to MPU6050

	RCC_GPIOC_CLK_EN();
	RCC_USART2_CLK_EN();

	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();

	RCC_AFIO_CLK_EN();
	RCC_TIMER2_CLK_EN();
	RCC_I2C1_CLK_EN();

	TIMER2_Init(RCC_CLK_36M);
}


int main(void) {

	Clock_Init();


//	UART_Config UART_Cfg;
//	UART_Cfg.BaudRate = UART_BaudRate_9600;
//	UART_Cfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;
//	UART_Cfg.IRQ_Enable = UART_IRQ_Enable_NONE;
//	UART_Cfg.P_IRQ_CallBack = NULL;
//	UART_Cfg.Parity = UART_Parity_NONE;
//	UART_Cfg.Payload_length = UART_Payload_Length_8B;
//	UART_Cfg.StopBits = UART_StopBits_1;
//	UART_Cfg.USART_Mode = UART_Mode_Tx_Rx;

	// 			Usage
	// -- Timer 2 for delay purposes ?
	// -- UART 2  ?
	// PA2 --> Tx
	// PA3 --> Rx
	// MPU after Timer change ?
	// PB6: I2C1_SCL
	// PB7: I2C1_SDA
	// B1, B9, A6 Check for PWM ?
	// Timer3 CH4 --> B1 @@ Timer4 CH4 --> B9
	// Timer3 CH1 --> A6



	// Should be uncommented

	//	MCAL_UART_Init(USART2, &UART_Cfg);
	//
	//	MCAL_UART_GPIO_SetPins(USART2);

	//	TIMER2_Init(RCC_CLK_36M);


	// For MPU
	//	MPU6050_Init();
	//	MPU6050_CalculateError();




	GPIO_PinConfig_t StepperDirPin = {
			.GPIO_PinNumber = GPIO_PIN_9,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	Stepper_Init(&StepperDirPin);


	while (1) {
		//		MPU6050_GetReadings(&roll_str, &pitch_str, &yaw_str);
		//
		//		MCAL_UART_SendString(USART2, "Roll: ", Enable);
		//		MCAL_UART_SendString(USART2, roll_str, Enable);
		//
		//		MCAL_UART_SendString(USART2, "Pitch: ", Enable);
		//		MCAL_UART_SendString(USART2, pitch_str, Enable);
		//
		//		MCAL_UART_SendString(USART2, "Yaw: ", Enable);
		//		MCAL_UART_SendString(USART2, yaw_str, Enable);


		// B1, B9, A6
		// Timer3 --> CH4
//		Stepper_Move_Steps(TIMER3, TIMER_CH4, 200, 50, 500, Stepper_UP);  // B1 Checked
//		Stepper_Move_Steps(TIMER3, TIMER_CH1, 200, 50, 500, Stepper_UP);  // A6 Checked
//		Stepper_Move_Steps(TIMER4, TIMER_CH4, 200, 50, 500, Stepper_UP);  // B9
		Stepper_Move_Steps(TIMER4, TIMER_CH3, 200, 50, 500, Stepper_UP);  // B8 Checked

		Delay_ms(1000);

	}
}

