/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_gpio_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_TIMER_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_RCC_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_USART_driver.h"


#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include "../Src/HAL/LCD/LCD_Interface.h"
#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"


#include "../Src/HAL/Stepper/Stepper.h"


#include "../Src/HAL/includes/DC_Motor.h"


#define START_PARKING       'B'
#define FINISH_PARKING        'C'

#define RECEIVED_OK         'D'

#define PARKING_REQUEST       'E'  // For now, mapping to 1 in DB.

#define FIRST_REKEB         'F'
#define FIRST_HOME          'G'

#define ARRIVED_INFRONTOF_SLOT    'H'
#define ARRIVED_AT_ENTRY      'I'
#define DONE_PARKING        'J'

#define IM_DONE               'K'

#define RETRIEVAL_REQUEST     'L'
#define START_RETRIEVING       'M'
#define FINISH_RETRIEVING        'N'
#define DONE_RETREIVING			'O'

#define LIFTING_INIT		'U'
#define ELEV_INIT			'V'

#define ACK_SLOT_NUMBER 'Y'

#define DELAY_SLOT_TO_SLOT 					700
#define DELAY_PROCESS_TO_PROCESS			3000


#define MOTORS_SPEED	80



volatile uint8_t RecievedFromServer = 0;


int SlotNumber = 0;

uint8_t PreviousReceived = 0;

volatile uint8_t isRetrieving = 0;
volatile uint8_t isAParking = 0;


uint16_t mySendChar = 0;




typedef enum{
	Idle=0,
	Wait_Slot_Number,
	Wait_First_Rekeb,
	Wait_Done_Parking,
	Done_First_Home,
	Wait_First_Done,
	DUMMY
}Robot_State;


uint16_t Buffer = 'Z';






volatile uint8_t newMessageArrived = 0;

volatile uint8_t initialSeverResponse = 0;





Robot_State MyCurrentState = DUMMY;


// Test succedded ----------------------------------------------------
void UART_Receiver_Callback(void)
{

	MCAL_UART_ReceiveData(USART2, &initialSeverResponse, Disable);
	if(initialSeverResponse == PARKING_REQUEST || initialSeverResponse == RETRIEVAL_REQUEST){
		newMessageArrived = 1;
		if(initialSeverResponse == PARKING_REQUEST)
			isAParking = 1;
		else if(initialSeverResponse == RETRIEVAL_REQUEST)
			isRetrieving = 1;
	}
	MCAL_UART_SendData(USART2, &Buffer, Enable);
}

// ------------------------------------------------------------------


void Clock_Init();



uint8_t Done_Arriving_At_Slot_Forward = 0;
uint8_t Done_Arriving_At_Slot_Backward = 0;


uint8_t DoneSending = 0;

int main(void) {



	Clock_Init();

	UART_Config UART_Cfg;
	UART_Cfg.BaudRate = UART_BaudRate_115200;
	UART_Cfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;
	UART_Cfg.IRQ_Enable = UART_IRQ_Enable_RXNE;
	UART_Cfg.P_IRQ_CallBack = UART_Receiver_Callback;
	UART_Cfg.Parity = UART_Parity_NONE;
	UART_Cfg.Payload_length = UART_Payload_Length_8B;
	UART_Cfg.StopBits = UART_StopBits_1;
	UART_Cfg.USART_Mode = UART_Mode_Tx_Rx;
	MCAL_UART_Init(USART2, &UART_Cfg);
	MCAL_UART_GPIO_SetPins(USART2);




	Motor_Config_t DC_Motor1 =
	{
			.DC_Pin1Number = GPIO_PIN_4,
			.DC_Pin2Number = GPIO_PIN_5,
			.DC_PortNumber1 = GPIOA,
			.DC_PortNumber2 = GPIOA,
			.PWM_Timer = TIMER3, //A6
			.PWM_Channel = TIMER_CH1
	};
	Motor_Config_t DC_Motor2 =
	{
			.DC_Pin1Number = GPIO_PIN_7,
			.DC_Pin2Number = GPIO_PIN_0,
			.DC_PortNumber1 = GPIOA,
			.DC_PortNumber2 = GPIOB,
			.PWM_Timer = TIMER3, // B1
			.PWM_Channel = TIMER_CH4
	};


	Motor_intialize(&DC_Motor1);

	Motor_intialize(&DC_Motor2);

	GPIO_PinConfig_t RED_StepperDirPin = {
			.GPIO_PinNumber = GPIO_PIN_8,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	GPIO_PinConfig_t BLUE_StepperDirPin = {
			.GPIO_PinNumber = GPIO_PIN_6,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	GPIO_PinConfig_t IR = {
			.GPIO_PinNumber = GPIO_PIN_13,
			.GPIO_MODE = GPIO_MODE_INPUT_FLOATING,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	MCAL_GPIO_Init(GPIOC, &IR);
	Stepper_Init(&RED_StepperDirPin);
	Stepper_Init(&BLUE_StepperDirPin);





	while (1) {


		// Green , Purble. Brown, white --> starting from end of first driver
		// Map

		//		Stepper_Move(2000, Stepper_UP);
		//
		//
		//		Delay_Timer1_ms(7000);




		if(newMessageArrived)
		{
			newMessageArrived = 0;
			if(MyCurrentState == DUMMY)
			{
				MyCurrentState = Idle;
			}
		}



		switch(MyCurrentState)
		{
		case Idle:
		{
			if(initialSeverResponse == PARKING_REQUEST || initialSeverResponse == RETRIEVAL_REQUEST || PreviousReceived == PARKING_REQUEST || PreviousReceived == RETRIEVAL_REQUEST ){
				PreviousReceived = initialSeverResponse;

				USART_Disable_IRQ();


				Done_Arriving_At_Slot_Forward = 0;
				Done_Arriving_At_Slot_Backward = 0;
				mySendChar = RECEIVED_OK;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);


				RecievedFromServer = RecievedFromServer - '0';

				if(RecievedFromServer >= 1 && RecievedFromServer <= 6){
					SlotNumber = RecievedFromServer;
					MyCurrentState = Wait_Slot_Number;
				}
			}
		}
		break;


		case Wait_Slot_Number:
		{
			mySendChar = ACK_SLOT_NUMBER;

			MCAL_UART_SendData(USART2, &mySendChar, Enable);



			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

			if(RecievedFromServer == FIRST_REKEB){
				MyCurrentState = Wait_First_Rekeb;
			}


		}
		break;


		case Wait_First_Rekeb:
		{
			mySendChar = 0;

			if(isAParking)
			{
				mySendChar = START_PARKING;
			}
			if(isRetrieving)
			{
				mySendChar = START_RETRIEVING;
			}

			//				mySendChar = START_PARKING;
			MCAL_UART_SendData(USART2, &mySendChar, Enable);


			// 3- Move forward -- distance (Main Track)

			while(!Done_Arriving_At_Slot_Forward)
			{

				if((SlotNumber - 1 ))
				{
					Motor_Move_ForWard(&DC_Motor1, MOTORS_SPEED);
					Motor_Move_ForWard(&DC_Motor2, MOTORS_SPEED);
					Delay_Timer1_ms(DELAY_SLOT_TO_SLOT * (SlotNumber - 1));
					Motor_TurnOff(&DC_Motor1);
					Motor_TurnOff(&DC_Motor2);
				}

				Delay_Timer1_ms(DELAY_PROCESS_TO_PROCESS);


				//					Stepper_Move_Steps(TIMER4, TIMER_CH4, 800, 50, 700, Stepper_UP);  // B9 --> RED Step
				//					Stepper_Move_Steps(TIMER4, TIMER_CH2, 800, 50, 1100, Stepper_UP);  // B7 --> BLUE Step

				Done_Arriving_At_Slot_Forward = 1;
			}


			mySendChar = ARRIVED_INFRONTOF_SLOT;
			MCAL_UART_SendData(USART2, &mySendChar, Enable);

			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			if(RecievedFromServer == DONE_PARKING || RecievedFromServer == DONE_RETREIVING){
				MyCurrentState = Wait_Done_Parking;

			}


		}
		break;


		case Wait_Done_Parking:
		{
			while(!Done_Arriving_At_Slot_Backward)
			{
				if((SlotNumber - 1 ))
				{
					Motor_Move_BackWard(&DC_Motor1, MOTORS_SPEED);
					Motor_Move_BackWard(&DC_Motor2, MOTORS_SPEED);
					Delay_Timer1_ms(DELAY_SLOT_TO_SLOT * (SlotNumber - 1));
					Motor_TurnOff(&DC_Motor1);
					Motor_TurnOff(&DC_Motor2);
				}

				Delay_Timer1_ms(DELAY_PROCESS_TO_PROCESS);
				Done_Arriving_At_Slot_Backward = 1;

				// 8- Lower the other robot
				//					Stepper_Move_Steps(TIMER4, TIMER_CH4, 800, 50, 700, Stepper_Down);  // B9 --> Step
				//					Stepper_Move_Steps(TIMER4, TIMER_CH2, 800, 50, 1100, Stepper_Down);  // B7 --> Step
			}


			mySendChar = ARRIVED_AT_ENTRY;
			MCAL_UART_SendData(USART2, &mySendChar, Enable);

			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);


			if(RecievedFromServer == FIRST_HOME){
				MyCurrentState = Done_First_Home;
			}


		}
		break;


		case Done_First_Home:
		{
			if(isAParking)
			{
				mySendChar = FINISH_PARKING;
			}else if(isRetrieving)
			{
				mySendChar = FINISH_RETRIEVING;
			}

			//				mySendChar = FINISH_PARKING;
			MCAL_UART_SendData(USART2, &mySendChar, Enable);


			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);



			if(RecievedFromServer == IM_DONE)
			{
				MyCurrentState = Wait_First_Done;
			}

		}
		break;



		case Wait_First_Done:
		{
			isAParking = 0;
			isRetrieving = 0;
			MyCurrentState = Idle;
			initialSeverResponse = 0;
			PreviousReceived = 0;

			USART_Enable_IRQ();
		}
		break;


		case DUMMY:
		{

		}
		break;

		}


	}
}



void Clock_Init()
{
	MCAL_RCC_CLK_Init(HSE_CLK, RCC_CLK_72M);  // is a must due to MPU6050

	RCC_GPIOC_CLK_EN();
	RCC_USART2_CLK_EN();

	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();

	RCC_AFIO_CLK_EN();
	RCC_I2C1_CLK_EN();

	TIMER1_Init(RCC_CLK_36M);

}





