/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_gpio_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_TIMER_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_RCC_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_USART_driver.h"


#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include "../Src/HAL/LCD/LCD_Interface.h"
#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"

#include "../Src/HAL/includes/MPU6050.h"


#include "../Src/HAL/Stepper/Stepper.h"


#include "../Src/HAL/includes/DC_Motor.h"

// PID Variables

#define TARGET_DISTANCE_MIN 2
#define TARGET_DISTANCE_MAX

float Kp = 0.5; 	// Proportional gain
float Ki = 0.001; 	// Integral gain
float Kd = 0.05; 	// Derivative gain


// MPU Variables
extern float AccErrorX, AccErrorY;
extern int GyroErrorX, GyroErrorY, GyroErrorZ;

char buffer[5];
char yaw_str[5];
char pitch_str[5];
char roll_str[5];


void Clock_Init(void);





int main(void) {

	Clock_Init();


	// ----------------- UART Usage --------------------------
	//	UART_Config UART_Cfg;
	//	UART_Cfg.BaudRate = UART_BaudRate_9600;
	//	UART_Cfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;
	//	UART_Cfg.IRQ_Enable = UART_IRQ_Enable_NONE;
	//	UART_Cfg.P_IRQ_CallBack = NULL;
	//	UART_Cfg.Parity = UART_Parity_NONE;
	//	UART_Cfg.Payload_length = UART_Payload_Length_8B;
	//	UART_Cfg.StopBits = UART_StopBits_1;
	//	UART_Cfg.USART_Mode = UART_Mode_Tx_Rx;

	//	MCAL_UART_Init(USART2, &UART_Cfg);
	//	MCAL_UART_GPIO_SetPins(USART2);


	// ----------------- MPU Usage --------------------------
	//	MPU6050_Init();
	//	MPU6050_CalculateError();



	// ------------------ Motors Configuration --------------
	Motor_Config_t DC_Motor1 =
	{
			.DC_Pin1Number = GPIO_PIN_9,
			.DC_Pin2Number = GPIO_PIN_10,
			.DC_PortNumber = GPIOA,
			.PWM_Timer = TIMER4,
			.PWM_Channel = TIMER_CH2
	};
	Motor_Config_t DC_Motor2 =
	{
			.DC_Pin1Number = GPIO_PIN_11,
			.DC_Pin2Number = GPIO_PIN_12,
			.DC_PortNumber = GPIOA,
			.PWM_Timer = TIMER4,
			.PWM_Channel = TIMER_CH1
	};

	Motor_intialize(&DC_Motor1);

	Motor_intialize(&DC_Motor2);


	GPIO_PinConfig_t StepperDirPin = {
			.GPIO_PinNumber = GPIO_PIN_9,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	Stepper_Init(&StepperDirPin);



	LCD_enuInit(&LCD_Configs);

	HC_SR04_Init(UltraSonic_Configs);


	// Local variables
	uint32_t Ultra1Distance = 0;
	uint32_t Ultra2Distance = 0;

	float integral = 0;
	float derivative = 0;
	float error = 0;
	float error_previous = 0;
	int correction_steps = 0;


	while (1) {

		// Main algorithm

		if(PinStepper_flag == 1)
		{
			MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_LOW);
			PinStepper_flag = 0;
		}


		LCD_enuJumpCursorTo(1, 0);
		LCD_enuSendString("START");

		HC_SR04_ReadDistance(0,&Ultra1Distance);
		HC_SR04_ReadDistance(1,&Ultra2Distance);

		LCD_enuJumpCursorTo(1, 0);
		LCD_enuSendString("Reading ");

		LCD_enuJumpCursorTo(2, 0);
		LCD_enuSendString("1st:    ");
		LCD_enuJumpCursorTo(2, 5);
		LCD_enuDisplayIntNum(Ultra1Distance);

		LCD_enuJumpCursorTo(2, 9);
		LCD_enuSendString("2nd:    ");
		LCD_enuJumpCursorTo(2, 13);
		LCD_enuDisplayIntNum(Ultra2Distance);



		if (Ultra1Distance <= 5) {

			MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_LOW);
			MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_LOW);

			Motor_Move_ForWard(&DC_Motor1, 100);
			Motor_Move_ForWard(&DC_Motor2, 100);

			Delay_Timer3_ms(2000);

			Motor_TurnOff(&DC_Motor1);
			Motor_TurnOff(&DC_Motor2);

			Delay_Timer3_ms(1000);

			if(Ultra2Distance<=2){
				// 8000 =~ 2cm
						// Move stepper up
				Stepper_Move_Steps(TIMER2, TIMER_CH1, 8000, 50, 500, Stepper_UP);

			}else if(Ultra2Distance>=4){ // 5
				// Move stepper down
				Stepper_Move_Steps(TIMER2, TIMER_CH1, 8000, 50, 500, Stepper_Down);

			} // 3
			else{

				// Calculate error
				error = TARGET_DISTANCE_MAX - Ultra2Distance;

				do{
					// Proportional term
					float P = Kp * error;

					// Integral term
					if (Ki != 0) {
						integral += error;
						if (integral > 100)
							integral = 100;
						else if (integral < -100)
							integral = -100;
					} else {
						integral = 0;
					}
					float I = Ki * integral;

					// Derivative term
					derivative = error - error_previous;
					float D = Kd * derivative;

					// Calculate PID output
					correction_steps = P + I + D;

					// Limit correction steps to avoid excessive adjustments
					if (correction_steps > 100) {
						correction_steps = 100;
					} else if (correction_steps < -100) {
						correction_steps = -100;
					}
					Stepper_Move_Steps(TIMER2, TIMER_CH1,(uint16_t)(1500 + correction_steps), 50, 500, Stepper_UP);
					// Update previous error for next iteration
					error_previous = error;

					//					Delay_Timer3_ms(1000);

					// re-read the distance
					HC_SR04_ReadDistance(1,&Ultra2Distance);
					LCD_enuJumpCursorTo(2, 9);
					LCD_enuSendString("2nd:    ");
					LCD_enuJumpCursorTo(2, 13);
					LCD_enuDisplayIntNum(Ultra2Distance);

					// re-Calculate error
					error = TARGET_DISTANCE_MAX - Ultra2Distance;

				}while(error);// control

			}

		}

		Delay_Timer3_ms(10);





		// Testing purposes


		// ------------- MPU Usage
		//		MPU6050_GetReadings(&roll_str, &pitch_str, &yaw_str);
		//
		//		MCAL_UART_SendString(USART2, "Roll: ", Enable);
		//		MCAL_UART_SendString(USART2, roll_str, Enable);
		//
		//		MCAL_UART_SendString(USART2, "Pitch: ", Enable);
		//		MCAL_UART_SendString(USART2, pitch_str, Enable);
		//
		//		MCAL_UART_SendString(USART2, "Yaw: ", Enable);
		//		MCAL_UART_SendString(USART2, yaw_str, Enable);



		// ---------------- Testing PWM
		// B1, B9, A6
		// Timer3 --> CH4
		//		Stepper_Move_Steps(TIMER3, TIMER_CH4, 200, 50, 500, Stepper_UP);  // B1 Checked
		//		Stepper_Move_Steps(TIMER3, TIMER_CH1, 200, 50, 500, Stepper_UP);  // A6 Checked
		//		Stepper_Move_Steps(TIMER4, TIMER_CH4, 200, 50, 500, Stepper_UP);  // B9

		// Stepper_Move_Steps(TIMER4, TIMER_CH3, 200, 50, 500, Stepper_UP);  // B8 Checked

		// Delay_ms(1000);

	}
}


void Clock_Init()
{
	MCAL_RCC_CLK_Init(HSE_CLK, RCC_CLK_72M);  // is a must due to MPU6050

	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();
	RCC_GPIOC_CLK_EN();

	RCC_USART2_CLK_EN();
	RCC_AFIO_CLK_EN();
	RCC_I2C1_CLK_EN();


	// Timer 3 for delay purposes
	RCC_TIMER3_CLK_EN();
	TIMER3_Init(RCC_CLK_36M);
}

