/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "Stm32_F103C6_Drivers/inc/Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_Drivers/inc/Stm32_F103C6_TIMER_driver.h"
#include "Stm32_F103C6_Drivers/inc/Stm32_F103C6_RCC_driver.h"

#include "HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include"HAL/DC_Motor/DC_Motor.h"
#include "HAL/LCD/LCD_Interface.h"

Motor_t motor_1={
		.Dc_motor[0].GPIO_PortNumber=GPIOB,
		.Dc_motor[0].GPIO_PinNumber=GPIO_PIN_11,
		.Dc_motor[0].GPIO_OUTPUT_SPEED=GPIO_SPEED_10MHZ,
		.Dc_motor[1].GPIO_PortNumber=GPIOB,
		.Dc_motor[1].GPIO_PinNumber=GPIO_PIN_12,
		.Dc_motor[1].GPIO_OUTPUT_SPEED=GPIO_SPEED_10MHZ
};

int main(void)
{

	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();
	RCC_TIMER2_CLK_EN();
	RCC_TIMER3_CLK_EN();


	uint8_t counter = 0;


	TIMER2_Init(RCC_CLK_8M);

	uint32_t UltraDistance = 0;

	GPIO_PinConfig_t DC_En1Pin = {
			.GPIO_PinNumber = GPIO_PIN_7,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	MCAL_GPIO_Init(GPIOA, &DC_En1Pin);

	GPIO_PinConfig_t DC_In1Pin = {
			.GPIO_PinNumber = GPIO_PIN_9,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	MCAL_GPIO_Init(GPIOA, &DC_In1Pin);

	GPIO_PinConfig_t DC_In2Pin = {
			.GPIO_PinNumber = GPIO_PIN_10,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	MCAL_GPIO_Init(GPIOA, &DC_In2Pin);


	GPIO_PinConfig_t DC_En2Pin = {
			.GPIO_PinNumber = GPIO_PIN_6,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	MCAL_GPIO_Init(GPIOA, &DC_En2Pin);

	GPIO_PinConfig_t DC_In3Pin = {
			.GPIO_PinNumber = GPIO_PIN_11,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	MCAL_GPIO_Init(GPIOA, &DC_In3Pin);

	GPIO_PinConfig_t DC_In4Pin = {
			.GPIO_PinNumber = GPIO_PIN_12,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	MCAL_GPIO_Init(GPIOA, &DC_In4Pin);


	HC_SR04_Init(&UltraSonic_Configs);
	//	GPIO_PinConfig_t test = {
	//			.GPIO_PinNumber = GPIO_PIN_12,
	//			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
	//			.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHZ,
	//	};
	//	MCAL_GPIO_Init(GPIOB, &test);


	LCD_enuInit(&LCD_Configs);



	//MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_12, GPIO_PIN_HIGH);

	//	MCAL_GPIO_Init(GPIOA, &DC_EnPin);
	//	MCAL_GPIO_Init(GPIOA, &DC_In1Pin);
	//	MCAL_GPIO_Init(GPIOA, &DC_In2Pin);

	//	TIMER3_Init(RCC_CLK_8M);

	//MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_HIGH);
	//MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_HIGH);




	//uint8_t counter = 0;
	Motor_intialize(&motor_1);



	/* Loop forever */
	while(1){

		Motor_Move_ForWard(&motor_1);
		Delay_ms(10);
		Motor_Move_BackWard(&motor_1);
		// -------------------- LCD Testing -----------------------------------------


		//		LCD_enuJumpCursorTo(1, 0);
		//		LCD_enuSendString("Reading ");
		//		//		// Port A6
		//		//
		//		//
		//		//		Lcd_ES_tsendString(LCD_Instant_1, "Hello Hamdy");
		//		//
		//		//

		// -------------------- UltraSonic Testing -----------------------------------

		//		HC_SR04_ReadDistance(&UltraDistance);





		//		LCD_enuJumpCursorTo(1, 9);
		//		LCD_enuSendString("is:     ");
		//		LCD_enuJumpCursorTo(1, 12);
		//		LCD_enuDisplayIntNum(UltraDistance);
		//
		//		Delay_ms(10);



		// --------------------- DC Motor Speed Testing (PWM) -----------------------


		//		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_HIGH);
		//		Delay_Timer3_ms(1000);
		//		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_LOW);
		//		Delay_Timer3_ms(1000);

		//		PWM(TIMER3, TIMER_CH1, counter, 1000, RCC_CLK_8M);
		//
		//		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_HIGH);
		//		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, GPIO_PIN_LOW);
		//		Delay_ms(1000);
		//
		//
		//		counter += 10;
		//
		//		if(counter > 100)
		//			counter = 0;

		//		Delay_ms(1000);
		//		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_LOW);
		//		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, GPIO_PIN_HIGH);
		//		Delay_ms(3000);


		//		PWM(TIMER3, TIMER_CH1, 100, 1000, RCC_CLK_8M);
		//


		// -------------------------- DC Motor Testing ---------------------------------


		HC_SR04_ReadDistance(&UltraDistance);


		LCD_enuJumpCursorTo(1, 0);
		LCD_enuSendString("Reading ");


		LCD_enuJumpCursorTo(1, 9);
		LCD_enuSendString("is:     ");
		LCD_enuJumpCursorTo(1, 12);
		LCD_enuDisplayIntNum(UltraDistance);

		if(UltraDistance <= 20)
		{





			// Timer3 CH2 --> A7  &&&& Timer3 CH1 --> A6


			PWM(TIMER3, TIMER_CH2, 100, 1000, RCC_CLK_8M);
			PWM(TIMER3, TIMER_CH1, 100, 1000, RCC_CLK_8M);



			// 9, 10 ---- 11,12
			MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_HIGH);
			MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, GPIO_PIN_LOW);
			//Delay_ms(1000);
			MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, GPIO_PIN_HIGH);
			MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_LOW);
			//Delay_ms(3000);


			counter += 10;

			if(counter > 100)
				counter = 0;

			Delay_ms(100);
		}



		Delay_ms(10);




	}
}
