/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "Stm32_F103C6_Drivers/inc/Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_Drivers/inc/Stm32_F103C6_TIMER_driver.h"
#include "Stm32_F103C6_Drivers/inc/Stm32_F103C6_RCC_driver.h"

#include "HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"

#include "HAL/LCD/LCD_Interface.h"

int main(void)
{

	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();


	uint32_t UltraDistance = 0;

	GPIO_PinConfig_t DC_EnPin = {
		.GPIO_PinNumber = GPIO_PIN_8,
		.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
		.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	GPIO_PinConfig_t DC_In1Pin = {
		.GPIO_PinNumber = GPIO_PIN_9,
		.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
		.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	GPIO_PinConfig_t DC_In2Pin = {
		.GPIO_PinNumber = GPIO_PIN_10,
		.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
		.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};


	HC_SR04_Init(&UltraSonic_Configs);
	GPIO_PinConfig_t test = {
			.GPIO_PinNumber = GPIO_PIN_5,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ,
	};
	MCAL_GPIO_Init(GPIOA, &test);
	LCD_enuInit(&LCD_Configs);

	MCAL_GPIO_Init(GPIOA, &DC_EnPin);
	MCAL_GPIO_Init(GPIOA, &DC_In1Pin);
	MCAL_GPIO_Init(GPIOA, &DC_In2Pin);

	TIMER3_Init(RCC_CLK_8M);

	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, GPIO_PIN_HIGH);




	//uint8_t counter = 0;


    /* Loop forever */
	while(1){


		LCD_enuJumpCursorTo(1, 0);
		LCD_enuSendString("Hi");
		// Port A6


		Lcd_ES_tsendString(LCD_Instant_1, "Hello Hamdy");


		HC_SR04_ReadDistance(&UltraDistance);


		if(UltraDistance > 50)
		{
			MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_HIGH);
		}else{
			MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_LOW);
		}
		Delay_Timer3_ms(1000);

		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_HIGH);
		Delay_Timer3_ms(1000);
		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_LOW);
		Delay_Timer3_ms(1000);

				PWM(TIMER3, TIMER_CH1, counter, 1000, RCC_CLK_8M);

		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_HIGH);
		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, GPIO_PIN_LOW);
		Delay_ms(1000);


		counter += 10;

		if(counter > 100)
			counter = 0;

		Delay_ms(1000);
		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_LOW);
		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, GPIO_PIN_HIGH);
		Delay_ms(3000);


		PWM(TIMER3, TIMER_CH1, 100, 1000, RCC_CLK_8M);

		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_HIGH);
		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, GPIO_PIN_LOW);
		Delay_ms(1000);
		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_9, GPIO_PIN_LOW);
		MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, GPIO_PIN_HIGH);
		Delay_ms(3000);


	}
}
