/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_gpio_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_TIMER_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_RCC_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_USART_driver.h"


#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include "../Src/HAL/LCD/LCD_Interface.h"
#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"

#include "../Src/HAL/includes/MPU6050.h"


#include "../Src/HAL/Stepper/Stepper.h"


#include "../Src/HAL/includes/DC_Motor.h"

#define TARGET_DISTANCE_MIN 2
#define TARGET_DISTANCE_MAX




extern float AccErrorX, AccErrorY;
extern int GyroErrorX, GyroErrorY, GyroErrorZ;


char buffer[5];
char yaw_str[5];
char pitch_str[5];
char roll_str[5];


//#define START_PARKING				'S'
//#define FINISH_PARKING				'F'
//
//
//#define RECEIVED_OK					'O'
//
//
//
//#define PARKING_REQUEST				'P'
//#define RETRIEVAL_REQUEST			'R'
//
//#define FIRST_REKEB					'K'
//#define FIRST_HOME					'H'
//
//#define ARRIVED_INFRONTOF_SLOT		'A'
//#define	ARRIVED_AT_ENTRY			'E'
//#define DONE_PARKING				'D'
//
//#define IM_DONE						'I'


#define START_PARKING				'4'
#define FINISH_PARKING				'2'


#define RECEIVED_OK					'2'



#define PARKING_REQUEST				'5'
#define RETRIEVAL_REQUEST			'6'

#define FIRST_REKEB					'3'
#define FIRST_HOME					'3'

#define ARRIVED_INFRONTOF_SLOT		'7'
#define	ARRIVED_AT_ENTRY			'4'
#define DONE_PARKING				'9'

#define IM_DONE               '8'



volatile uint8_t RecievedFromServer = 0;
volatile uint8_t isReceived_Server = 0;

volatile uint8_t RecievedFirstState = 0;
volatile uint8_t isReceived_FirstRobotState = 0;

volatile uint8_t isFirstRekeb = 0;
volatile uint8_t RecievedRekeb = 0;

volatile uint8_t isFirstHome = 0;
volatile uint8_t RecievedFirstHome = 0;


uint16_t mySendChar = 0;


volatile static uint8_t ReceivingCounter=0;


typedef enum{
	Idle=0,
	Parking_Started,
	Arrived_At_ParkingSlot,
	Arrived_At_Entry,
	Parking_Finished
}Robot_State;


uint16_t Buffer = 'Z';


//
void UART_RecieveFromServerCallBack(void)
{
	MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Disable);

	if(RecievedFromServer == 'S'){
		MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
		if(RecievedFromServer == 'H')
		{

			MCAL_UART_SendData(USART2, &Buffer, Enable);
			MCAL_UART_SendString(USART2, "Boll: ", Enable);
			MCAL_UART_SendString(USART2, roll_str, Enable);

			MCAL_UART_SendString(USART2, "Xitch: ", Enable);
			MCAL_UART_SendString(USART2, pitch_str, Enable);

			MCAL_UART_SendString(USART2, "Zaw: ", Enable);
			MCAL_UART_SendString(USART2, yaw_str, Enable);
		}
	}

	MCAL_UART_SendData(USART2, &Buffer, Enable);
}



volatile uint8_t newMessageArrived = 0;


Robot_State MyCurrentState = Idle;


// Test succedded ----------------------------------------------------
void UART_Test_Callback(void)
{
	MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
	if(RecievedFromServer == PARKING_REQUEST || RecievedFromServer == RETRIEVAL_REQUEST)
		newMessageArrived = 1;

	MCAL_UART_SendData(USART2, &Buffer, Enable);
}

// ------------------------------------------------------------------


void Clock_Init();



uint8_t Done_Moving_Forward = 0;
uint8_t Done_Moving_Backward = 0;


uint8_t DoneSending = 0;

int main(void) {



	Clock_Init();

	UART_Config UART_Cfg;
	UART_Cfg.BaudRate = UART_BaudRate_115200;
	UART_Cfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;
	UART_Cfg.IRQ_Enable = UART_IRQ_Enable_RXNE;
	UART_Cfg.P_IRQ_CallBack = UART_Test_Callback;
	UART_Cfg.Parity = UART_Parity_NONE;
	UART_Cfg.Payload_length = UART_Payload_Length_8B;
	UART_Cfg.StopBits = UART_StopBits_1;
	UART_Cfg.USART_Mode = UART_Mode_Tx_Rx;
	MCAL_UART_Init(USART2, &UART_Cfg);
	MCAL_UART_GPIO_SetPins(USART2);




	// 			Usage
	// -- Timer 2 for delay purposes ?
	// -- UART 2  ?
	// PA2 --> Tx
	// PA3 --> Rx
	// MPU after Timer change ?
	// PB6: I2C1_SCL
	// PB7: I2C1_SDA
	// B1, B9, A6 Check for PWM ?
	// Timer3 CH4 --> B1 @@ Timer4 CH4 --> B9
	// Timer3 CH1 --> A6



	// Should be uncommented


	//	TIMER2_Init(RCC_CLK_36M);


	// For MPU
	//	MPU6050_Init();
	//	MPU6050_CalculateError();



	Motor_Config_t DC_Motor1 =
	{
			.DC_Pin1Number = GPIO_PIN_4,
			.DC_Pin2Number = GPIO_PIN_5,
			.DC_PortNumber1 = GPIOA,
			.DC_PortNumber2 = GPIOA,
			.PWM_Timer = TIMER3, //A6
			.PWM_Channel = TIMER_CH1
	};
	Motor_Config_t DC_Motor2 =
	{
			.DC_Pin1Number = GPIO_PIN_7,
			.DC_Pin2Number = GPIO_PIN_0,
			.DC_PortNumber1 = GPIOA,
			.DC_PortNumber2 = GPIOB,
			.PWM_Timer = TIMER3, // B1
			.PWM_Channel = TIMER_CH4
	};


	Motor_intialize(&DC_Motor1);

	Motor_intialize(&DC_Motor2);

	GPIO_PinConfig_t Stepper1DirPin = {
			.GPIO_PinNumber = GPIO_PIN_8,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	GPIO_PinConfig_t Stepper2DirPin = {
			.GPIO_PinNumber = GPIO_PIN_6,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	GPIO_PinConfig_t IR = {
			.GPIO_PinNumber = GPIO_PIN_13,
			.GPIO_MODE = GPIO_MODE_INPUT_FLOATING,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	MCAL_GPIO_Init(GPIOC, &IR);
	Stepper_Init(&Stepper1DirPin);
	Stepper_Init(&Stepper2DirPin);





	while (1) {
		//		uint8_t IR_Reading = MCAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13);

		// Try change MPU6050 to interrupt mode

		//		MPU6050_GetReadings(&roll_str, &pitch_str, &yaw_str);
		//
		//		MCAL_UART_SendString(USART2, "Roll: ", Enable);
		//		MCAL_UART_SendString(USART2, roll_str, Enable);
		//
		//		MCAL_UART_SendString(USART2, "Pitch: ", Enable);
		//		MCAL_UART_SendString(USART2, pitch_str, Enable);
		//
		//		MCAL_UART_SendString(USART2, "Yaw: ", Enable);
		//		MCAL_UART_SendString(USART2, yaw_str, Enable);


		//		Buffer = 'Z';
		//		if(RecievedFromServer == 'S'){
		//			MCAL_UART_SendData(USART2, &Buffer, Enable);
		//			MCAL_UART_SendString(USART2, "Boll: ", Enable);
		//			MCAL_UART_SendString(USART2, roll_str, Enable);
		//
		//			MCAL_UART_SendString(USART2, "Xitch: ", Enable);
		//			MCAL_UART_SendString(USART2, pitch_str, Enable);
		//
		//			MCAL_UART_SendString(USART2, "Zaw: ", Enable);
		//			MCAL_UART_SendString(USART2, yaw_str, Enable);
		//		}
		//
		//		MCAL_UART_SendData(USART2, &Buffer, Enable);
		//		RecievedFromServer = 0;
		//		Buffer = 0;



		//		if(RecievedFromServer == PARKING_REQUEST){
		//			mySendChar = RECEIVED_OK;
		//			MCAL_UART_SendData(USART2, &mySendChar, Enable);
		//			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
		//		}
		//		if(RecievedFromServer == FIRST_REKEB){
		//			mySendChar = START_PARKING;
		//			MCAL_UART_SendData(USART2, &mySendChar, Enable);
		//
		//			MyCurrentState = Parking_Started;
		//
		//			// 3- Move forward -- distance (Main Track)
		//			Motor_Move_ForWard(&DC_Motor1, 100);
		//			Motor_Move_ForWard(&DC_Motor2, 100);
		//			Delay_Timer1_ms(1000);
		//			Motor_TurnOff(&DC_Motor1);
		//			Motor_TurnOff(&DC_Motor2);
		//
		//			mySendChar = ARRIVED_INFRONTOF_SLOT;
		//			MCAL_UART_SendData(USART2, &mySendChar, Enable);
		//
		//			MyCurrentState = Arrived_At_ParkingSlot;
		//			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
		//
		//		}
		//		if(RecievedFromServer == DONE_PARKING){
		//			// 7- Backward distance -- (Main track)
		//			Motor_Move_BackWard(&DC_Motor1, 100);
		//			Motor_Move_BackWard(&DC_Motor2, 100);
		//			Delay_Timer1_ms(1000);
		//			Motor_TurnOff(&DC_Motor1);
		//			Motor_TurnOff(&DC_Motor2);
		//			// 8- Lower the other robot
		//			Stepper_Move_Steps(TIMER4, TIMER_CH4, 200, 50, 500, Stepper_Down);  // B9 --> Step
		//			Stepper_Move_Steps(TIMER4, TIMER_CH2, 200, 50, 500, Stepper_Down);  // B7 --> Step
		//
		//			mySendChar = ARRIVED_AT_ENTRY;
		//			MCAL_UART_SendData(USART2, &mySendChar, Enable);
		//
		//			MyCurrentState = Arrived_At_Entry;
		//			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
		//		}
		//		if(RecievedFromServer == FIRST_HOME){
		//			mySendChar = FINISH_PARKING;
		//			MCAL_UART_SendData(USART2, &mySendChar, Enable);
		//
		//			MyCurrentState = Parking_Finished;
		//			RecievedFromServer = 0;
		//		}


		if(newMessageArrived)
		{
			newMessageArrived = 0;


			if(RecievedFromServer == PARKING_REQUEST){

				Done_Moving_Backward = 0;
				Done_Moving_Forward = 0;
				mySendChar = RECEIVED_OK;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}
			if(RecievedFromServer == FIRST_REKEB){
				RecievedFromServer = 0;
				mySendChar = START_PARKING;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);

				MyCurrentState = Parking_Started;

				// 3- Move forward -- distance (Main Track)
				while(!Done_Moving_Forward)
				{
					Motor_Move_ForWard(&DC_Motor1, 100);
					Motor_Move_ForWard(&DC_Motor2, 100);
					Delay_Timer1_ms(3000);
					Motor_TurnOff(&DC_Motor1);
					Motor_TurnOff(&DC_Motor2);
					Done_Moving_Forward = 1;
					Stepper_Move_Steps(TIMER4, TIMER_CH4, 800, 50, 700, Stepper_UP);  // B9 --> Step
					Stepper_Move_Steps(TIMER4, TIMER_CH2, 800, 50, 700, Stepper_UP);  // B7 --> Step
					Delay_Timer1_ms(3000);
				}


				mySendChar = ARRIVED_INFRONTOF_SLOT;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);

				MyCurrentState = Arrived_At_ParkingSlot;
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}else{
				mySendChar = RECEIVED_OK;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}
			if(RecievedFromServer == DONE_PARKING){
				RecievedFromServer = 0;
				// 7- Backward distance -- (Main track)
				while(!Done_Moving_Backward)
				{
					Motor_Move_BackWard(&DC_Motor1, 100);
					Motor_Move_BackWard(&DC_Motor2, 100);
					Delay_Timer1_ms(3000);
					Motor_TurnOff(&DC_Motor1);
					Motor_TurnOff(&DC_Motor2);
					// 8- Lower the other robot
					Stepper_Move_Steps(TIMER4, TIMER_CH4, 800, 50, 700, Stepper_Down);  // B9 --> Step
					Stepper_Move_Steps(TIMER4, TIMER_CH2, 800, 50, 700, Stepper_Down);  // B7 --> Step
					Delay_Timer1_ms(3000);
					Done_Moving_Backward = 1;
				}


				mySendChar = ARRIVED_AT_ENTRY;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);

				MyCurrentState = Arrived_At_Entry;
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}else{
				mySendChar = ARRIVED_INFRONTOF_SLOT;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}
			if(RecievedFromServer == FIRST_HOME){
				RecievedFromServer = 0;
				mySendChar = FINISH_PARKING;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);

				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

				MyCurrentState = Parking_Finished;
				RecievedFromServer = 0;
			}else{
				mySendChar = ARRIVED_AT_ENTRY;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}
			if(RecievedFromServer == IM_DONE)
			{
				RecievedFromServer = 0;

			}else{
				mySendChar = FINISH_PARKING;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
			}
			MCAL_UART_SendData(USART2, &Buffer, Enable);



		}





		// Lifting Procedures



		//		//
		//		Delay_ms(1000);
		Delay_Timer1_ms(3000);


		//		}

	}
}



void Clock_Init()
{
	MCAL_RCC_CLK_Init(HSE_CLK, RCC_CLK_72M);  // is a must due to MPU6050

	RCC_GPIOC_CLK_EN();
	RCC_USART2_CLK_EN();

	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();

	RCC_AFIO_CLK_EN();
	RCC_TIMER2_CLK_EN();
	RCC_I2C1_CLK_EN();

	TIMER1_Init(RCC_CLK_36M);
	TIMER2_Init(RCC_CLK_36M);

}



