/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// bootloader 0x80000000

// code 0x8008000

// backup

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_gpio_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_TIMER_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_RCC_driver.h"
//
#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include "../Src/HAL/LCD/LCD_Interface.h"
#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_USART_driver.h"


#include "../Src/HAL/Stepper/Stepper.h"


#include "../Src/HAL/includes/DC_Motor.h"

#define TARGET_DISTANCE_MIN 2
#define TARGET_DISTANCE_MAX 4





#define START_PARKING       'B'
#define FINISH_PARKING        'C'

#define RECEIVED_OK         'D'

#define PARKING_REQUEST       'E' // 4

#define FIRST_REKEB         'F'
#define FIRST_HOME          'G'

#define ARRIVED_INFRONTOF_SLOT    'H'
#define ARRIVED_AT_ENTRY      'I'
#define DONE_PARKING        'J'

#define IM_DONE               'K'

#define RETRIEVAL_REQUEST     'L' // 11
#define START_RETRIEVING       'M'
#define FINISH_RETRIEVING        'N'
#define DONE_RETREIVING			'O'

#define CAR_ARRIVED				'P'


#define ACK_STARTING			'Q'
#define ACK_DONE				'R'
#define ACK_CAR_ARRIVED				'S'
#define ACK_ARIV_AT_SLOT		'T'


#define LIFTING_INIT		'U'
#define ELEV_INIT			'V'


#define DELAY_HOME_ELEVATOR   	1800
#define DELAY_ELEVATOR_PARKING 	1850

#define MOTOR_SPEED			 	40



volatile uint8_t RecievedFromServer = 0;
volatile uint8_t isReceived_Server = 0;

volatile uint8_t RecievedFirstState = 0;
volatile uint8_t isReceived_FirstRobotState = 0;

volatile uint8_t isFirstRekeb = 0;
volatile uint8_t RecievedRekeb = 0;

volatile uint8_t isFirstHome = 0;
volatile uint8_t RecievedFirstHome = 0;

uint8_t PreviousReceived = 0;


volatile uint8_t isRetrieving = 0;
volatile uint8_t isAParking = 0;


uint16_t mySendChar = 0;


volatile static uint8_t ReceivingCounter=0;



uint16_t Buffer = 'Z';

float Kp = 0.5; 	// Proportional gain
float Ki = 0.001; 	// Integral gain
float Kd = 0.05; 	// Derivative gain
char buffer[5];
char yaw_str[5];
char pitch_str[5];
char roll_str[5];


void Proceed_BackToHome(Motor_Config_t *Motor1, Motor_Config_t *Motor2);
void Proceed_Parking(Motor_Config_t *Motor1, Motor_Config_t *Motor2);



typedef enum{
	Idle=0,
	Wait_Car_Ack,
	Wait_Start_Parking,
	Wait_In_Front_Of_Slot,
	Wait_Arriving_At_Entry,
	Wait_Finish_Parking,
	Wait_ACK_Done,
	DUMMY
}Robot_State;


Robot_State MyCurrentState = Idle;



//

volatile uint8_t newMessageArrived = 0;


volatile uint8_t initialSeverResponse = 0;


uint32_t Ultra1Distance = 255;
uint32_t Ultra2Distance = 0;


#define STEPPER_STEPS	2500


uint8_t ProceedParking = 0;
uint8_t DoneHome = 0;
uint8_t UltraMove = 0;
uint8_t Done_Stepper_Up = 0, Done_Stepper_Down = 0;
uint8_t Done_Stepper_Up_R = 0, Done_Stepper_Down_R = 0;

float integral = 0;
float derivative = 0;

float error = 0;
float error_previous = 0;
int correction_steps = 0;

// Test succedded ----------------------------------------------------
void UART_Receiver_Callback(void)
{

	MCAL_UART_ReceiveData(USART2, &initialSeverResponse, Disable);
	if(initialSeverResponse == PARKING_REQUEST || initialSeverResponse == RETRIEVAL_REQUEST){
		newMessageArrived = 1;
		if(initialSeverResponse == PARKING_REQUEST)
			isAParking = 1;
		else if(initialSeverResponse == RETRIEVAL_REQUEST)
			isRetrieving = 1;
	}
	MCAL_UART_SendData(USART2, &Buffer, Enable);
}




int main(void) {

	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();
	RCC_GPIOC_CLK_EN();
	RCC_AFIO_CLK_EN();
	RCC_TIMER1_CLK_EN();
	MCAL_RCC_CLK_Init(HSE_CLK, RCC_CLK_72M);  // is a must due to MPU6050

	RCC_USART2_CLK_EN();
	TIMER1_Init(RCC_CLK_36M);
	Motor_Config_t DC_Motor1 =
	{
			.DC_Pin1Number = GPIO_PIN_4,
			.DC_Pin2Number = GPIO_PIN_5,
			.DC_PortNumber1 = GPIOA,
			.DC_PortNumber2 = GPIOA,
			.PWM_Timer = TIMER3,
			.PWM_Channel = TIMER_CH1
	};
	Motor_Config_t DC_Motor2 =
	{
			.DC_Pin1Number = GPIO_PIN_7,
			.DC_Pin2Number = GPIO_PIN_0,
			.DC_PortNumber1 = GPIOA,
			.DC_PortNumber2 = GPIOB,
			.PWM_Timer = TIMER3,
			.PWM_Channel = TIMER_CH4
	};


	GPIO_PinConfig_t StepperDirPin = {
			.GPIO_PinNumber = GPIO_PIN_8,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	GPIO_PinConfig_t LedPin = {
			.GPIO_PinNumber = GPIO_PIN_13,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};
	MCAL_GPIO_Init(GPIOC, &LedPin);


	UART_Config UART_Cfg;
	UART_Cfg.BaudRate = UART_BaudRate_115200;
	UART_Cfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;
	UART_Cfg.IRQ_Enable = UART_IRQ_Enable_RXNE;
	UART_Cfg.P_IRQ_CallBack = UART_Receiver_Callback;
	UART_Cfg.Parity = UART_Parity_NONE;
	UART_Cfg.Payload_length = UART_Payload_Length_8B;
	UART_Cfg.StopBits = UART_StopBits_1;
	UART_Cfg.USART_Mode = UART_Mode_Tx_Rx;
	MCAL_UART_Init(USART2, &UART_Cfg);
	MCAL_UART_GPIO_SetPins(USART2);


	Motor_intialize(&DC_Motor1);

	Motor_intialize(&DC_Motor2);

	LCD_enuInit(&LCD_Configs);

	HC_SR04_Init(UltraSonic_Configs);
	Stepper_Init(&StepperDirPin);



	/* Loop forever */
	while (1) {
		switch(MyCurrentState)
		{
		case Idle:
		{

			if(initialSeverResponse == PARKING_REQUEST || initialSeverResponse == RETRIEVAL_REQUEST || PreviousReceived == PARKING_REQUEST || PreviousReceived == RETRIEVAL_REQUEST ){
				PreviousReceived = initialSeverResponse;


				USART_Disable_IRQ();


				mySendChar = RECEIVED_OK;

				MCAL_UART_SendData(USART2, &mySendChar, Enable);


				if(!Done_Stepper_Up && !(initialSeverResponse == RETRIEVAL_REQUEST))
				{
					Stepper_Move_Steps(TIMER4, TIMER_CH4, STEPPER_STEPS, 50, 700, Stepper_UP);  // B9 --> Step
					Delay_Timer1_ms(4000);

					Done_Stepper_Up = 1;
				}

				if(initialSeverResponse != RETRIEVAL_REQUEST){
					do{
						HC_SR04_ReadDistance(0, &Ultra1Distance);
						Delay_Timer1_ms(80);

					}while(Ultra1Distance > 20);
				}

				mySendChar = CAR_ARRIVED;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

				if(RecievedFromServer == ACK_CAR_ARRIVED)
				{
					MyCurrentState = Wait_Car_Ack;
				}

			}
		}
		break;


		case Wait_Car_Ack:
		{
			// Move to the Elevator, then send a "FIRST_REKEB"
			LCD_enuJumpCursorTo(1, 0);
			LCD_enuSendString("GOING_ToElevator");

			if(!UltraMove)
			{
				Motor_Move_ForWard(&DC_Motor1, MOTOR_SPEED);
				Motor_Move_ForWard(&DC_Motor2, MOTOR_SPEED);
				Delay_Timer1_ms(DELAY_HOME_ELEVATOR);
				Motor_TurnOff(&DC_Motor1);
				Motor_TurnOff(&DC_Motor2);

				Delay_Timer1_ms(2000);

				UltraMove = 1;
			}



			LCD_enuJumpCursorTo(1, 0);
			LCD_enuSendString("AT Elevator");
			mySendChar = FIRST_REKEB;
			MCAL_UART_SendData(USART2, &mySendChar, Enable);
			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

			if(RecievedFromServer == START_PARKING)
			{
				MyCurrentState = Wait_Start_Parking;
			}
		}
		break;



		case Wait_Start_Parking:
		{

			mySendChar = ACK_STARTING;
			MCAL_UART_SendData(USART2, &mySendChar, Enable);

			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

			if(RecievedFromServer == ARRIVED_INFRONTOF_SLOT)
			{
				MyCurrentState = Wait_In_Front_Of_Slot;
			}

		}

		break;



		case Wait_In_Front_Of_Slot:
		{
			if(!ProceedParking)
			{
				Motor_Move_ForWard(&DC_Motor1, MOTOR_SPEED);
				Motor_Move_ForWard(&DC_Motor2, MOTOR_SPEED);
				Delay_Timer1_ms(DELAY_ELEVATOR_PARKING);
				Motor_TurnOff(&DC_Motor1);
				Motor_TurnOff(&DC_Motor2);


				if(!Done_Stepper_Down && initialSeverResponse == PARKING_REQUEST)
				{
					Stepper_Move_Steps(TIMER4, TIMER_CH4, STEPPER_STEPS, 50, 700, Stepper_Down);  // B9 --> Step
					Delay_Timer1_ms(4000);

					Done_Stepper_Down = 1;
				}
				else if (!Done_Stepper_Down && initialSeverResponse == RETRIEVAL_REQUEST){

					Stepper_Move_Steps(TIMER4, TIMER_CH4, STEPPER_STEPS, 50, 700, Stepper_UP);  // B9 --> Step
					Delay_Timer1_ms(4000);

					Done_Stepper_Down = 1;
				}





				Motor_Move_BackWard(&DC_Motor1, 60);
				Motor_Move_BackWard(&DC_Motor2, 60);
				Delay_Timer1_ms(1800);
				Motor_TurnOff(&DC_Motor1);
				Motor_TurnOff(&DC_Motor2);

				Delay_Timer1_ms(4000);

				ProceedParking = 1;
			}


			mySendChar = DONE_PARKING;
			MCAL_UART_SendData(USART2, &mySendChar, Enable);
			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

			if(RecievedFromServer == ARRIVED_AT_ENTRY)
			{
				MyCurrentState = Wait_Arriving_At_Entry;
			}
		}
		break;


		case Wait_Arriving_At_Entry:
		{


			if(!DoneHome)
			{
				Motor_Move_BackWard(&DC_Motor1, 60);
				Motor_Move_BackWard(&DC_Motor2, 60);
				Delay_Timer1_ms(1400);
				Motor_TurnOff(&DC_Motor1);
				Motor_TurnOff(&DC_Motor2);

				Delay_Timer1_ms(4000);

				DoneHome = 1;
			}





			mySendChar = FIRST_HOME;
			MCAL_UART_SendData(USART2, &mySendChar, Enable);
			MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

			if(RecievedFromServer == FINISH_PARKING)
			{
				MyCurrentState = Wait_Finish_Parking;
			}

		}
		break;


		case Wait_Finish_Parking:
		{
			if(RecievedFromServer == FINISH_PARKING )
			{
				mySendChar = IM_DONE;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

				if(RecievedFromServer == ACK_DONE)
				{
					MyCurrentState = Wait_ACK_Done;
				}



			}
		}
		break;


		case Wait_ACK_Done:
		{
			LCD_enuJumpCursorTo(1, 0);
			LCD_enuSendString("AT HOME");

			if(!Done_Stepper_Up_R && initialSeverResponse == RETRIEVAL_REQUEST)
			{
				Stepper_Move_Steps(TIMER4, TIMER_CH4, STEPPER_STEPS, 50, 700, Stepper_Down);  // B9 --> Step
				Delay_Timer1_ms(4000);

				Done_Stepper_Up_R = 1;
			}

			isAParking = 0;
			isRetrieving = 0;
			MyCurrentState = Idle;
			initialSeverResponse = 0;
			PreviousReceived = 0;
			ProceedParking = 0;
			DoneHome = 0;
			UltraMove = 0;
			Done_Stepper_Down = 0;
			Done_Stepper_Up = 0;


			USART_Enable_IRQ();



		}

		break;


		case DUMMY:
		{

		}
		break;

		}


	}
}





void Proceed_Parking(Motor_Config_t *Motor1, Motor_Config_t *Motor2)
{
	LCD_enuJumpCursorTo(1, 0);
	LCD_enuSendString("START");

	//HC_SR04_ReadDistance(0,&Ultra1Distance);
	//HC_SR04_ReadDistance(1,&Ultra2Distance);

	LCD_enuJumpCursorTo(1, 0);
	LCD_enuSendString("Reading ");

	LCD_enuJumpCursorTo(2, 0);
	LCD_enuSendString("1st:    ");
	LCD_enuJumpCursorTo(2, 5);
	LCD_enuDisplayIntNum(Ultra1Distance);

	LCD_enuJumpCursorTo(2, 9);
	LCD_enuSendString("2nd:    ");
	LCD_enuJumpCursorTo(2, 13);
	LCD_enuDisplayIntNum(Ultra2Distance);

	Motor_Move_ForWard(Motor1, MOTOR_SPEED);
	Motor_Move_ForWard(Motor2, MOTOR_SPEED);

	Delay_Timer1_ms(1000);

	Motor_TurnOff(Motor1);
	Motor_TurnOff(Motor2);

	Delay_Timer1_ms(500);

	if(Ultra2Distance<=2){
		// 8000 =~ 2cm
		// Move stepper up
		Stepper_Move_Steps(TIMER4, TIMER_CH4, 800, 50, 700, Stepper_UP);  // B9 --> Step

	}else if(Ultra2Distance>=4){ // 5
		// Move stepper down
		Stepper_Move_Steps(TIMER4, TIMER_CH4, 800, 50, 700, Stepper_Down);  // B9 --> Step
		//
	} // 3
	else{

		// Calculate error
		error = TARGET_DISTANCE_MAX - Ultra2Distance;

		do{
			// Proportional term
			float P = Kp * error;

			// Integral term
			if (Ki != 0) {
				integral += error;
				if (integral > 100)
					integral = 100;
				else if (integral < -100)
					integral = -100;
			} else {
				integral = 0;
			}
			float I = Ki * integral;

			// Derivative term
			derivative = error - error_previous;
			float D = Kd * derivative;

			// Calculate PID output
			correction_steps = P + I + D;

			// Limit correction steps to avoid excessive adjustments
			if (correction_steps > 100) {
				correction_steps = 100;
			} else if (correction_steps < -100) {
				correction_steps = -100;
			}
			Stepper_Move_Steps(TIMER2, TIMER_CH1,(uint16_t)(1500 + correction_steps), 50, 500, Stepper_UP);
			// Update previous error for next iteration
			error_previous = error;

			//					Delay_Timer1_ms(1000);

			// re-read the distance
			HC_SR04_ReadDistance(1,&Ultra2Distance);
			LCD_enuJumpCursorTo(2, 9);
			LCD_enuSendString("2nd:    ");
			LCD_enuJumpCursorTo(2, 13);
			LCD_enuDisplayIntNum(Ultra2Distance);

			// re-Calculate error
			error = TARGET_DISTANCE_MAX - Ultra2Distance;

		}while(error);// control

	}

	Motor_Move_BackWard(Motor1, MOTOR_SPEED);
	Motor_Move_BackWard(Motor2, MOTOR_SPEED);

	Delay_Timer1_ms(1000);

	Motor_TurnOff(Motor1);
	Motor_TurnOff(Motor2);

	Delay_Timer1_ms(500);


}



void Proceed_BackToHome(Motor_Config_t *Motor1, Motor_Config_t *Motor2)
{
	Motor_Move_ForWard(Motor1, MOTOR_SPEED);
	Motor_Move_ForWard(Motor2, MOTOR_SPEED);

	Delay_Timer1_ms(1000);

	Motor_TurnOff(Motor1);
	Motor_TurnOff(Motor2);

	Delay_Timer1_ms(1000);
}














