/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// bootloader 0x80000000

// code 0x8008000

// backup

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_gpio_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_TIMER_driver.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_RCC_driver.h"
//
#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include "../Src/HAL/LCD/LCD_Interface.h"
#include "../Src/HAL/UltraSonic_HC_SR04/UltraSonic_Interface.h"
#include "../Src/Stm32_F103C6_Drivers/inc/Stm32_F103C6_USART_driver.h"


#include "../Src/HAL/Stepper/Stepper.h"


#include "../Src/HAL/includes/DC_Motor.h"

#define TARGET_DISTANCE_MIN 2
#define TARGET_DISTANCE_MAX 4





#define START_PARKING       'U'
#define FINISH_PARKING        'B'

#define RECEIVED_OK         'C'

#define PARKING_REQUEST       'D'

#define FIRST_REKEB         'F'
#define FIRST_HOME          'G'

#define ARRIVED_INFRONTOF_SLOT    'H'
#define ARRIVED_AT_ENTRY      'I'
#define DONE_PARKING        'J'

#define IM_DONE               'K'

#define RETRIEVAL_REQUEST     'E'
#define START_RETRIEVING       'L'
#define FINISH_RETRIEVING        'M'
#define DONE_RETREIVING			'N'

#define CAR_ARRIVED				'O'


#define ACK_STARTING			'P'
#define ACK_DONE				'Q'
#define ACK_CAR_ARRIVED				'R'
#define ACK_ARIV_AT_SLOT		'S'

volatile uint8_t RecievedFromServer = 0;
volatile uint8_t isReceived_Server = 0;

volatile uint8_t RecievedFirstState = 0;
volatile uint8_t isReceived_FirstRobotState = 0;

volatile uint8_t isFirstRekeb = 0;
volatile uint8_t RecievedRekeb = 0;

volatile uint8_t isFirstHome = 0;
volatile uint8_t RecievedFirstHome = 0;


uint16_t mySendChar = 0;


volatile static uint8_t ReceivingCounter=0;


typedef enum{
	Idle=0,
	Parking_Started,
	Arrived_At_ParkingSlot,
	Arrived_At_Entry,
	Parking_Finished
}Robot_State;


uint16_t Buffer = 'Z';

float Kp = 0.5; 	// Proportional gain
float Ki = 0.001; 	// Integral gain
float Kd = 0.05; 	// Derivative gain
char buffer[5];
char yaw_str[5];
char pitch_str[5];
char roll_str[5];


void Proceed_BackToHome(Motor_Config_t *Motor1, Motor_Config_t *Motor2);
void Proceed_Parking(Motor_Config_t *Motor1, Motor_Config_t *Motor2);


//

volatile uint8_t newMessageArrived = 0;


Robot_State MyCurrentState = Idle;
uint32_t Ultra1Distance = 0;
uint32_t Ultra2Distance = 0;

float integral = 0;
float derivative = 0;

float error = 0;
float error_previous = 0;
int correction_steps = 0;

// Test succedded ----------------------------------------------------
void UART_Test_Callback(void)
{
	MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
	if(RecievedFromServer == PARKING_REQUEST || RecievedFromServer == RETRIEVAL_REQUEST)
		newMessageArrived = 1;

	MCAL_UART_SendData(USART2, &Buffer, Enable);
}





int main(void) {

	RCC_GPIOB_CLK_EN();
	RCC_GPIOA_CLK_EN();
	RCC_AFIO_CLK_EN();
	RCC_TIMER1_CLK_EN();
	MCAL_RCC_CLK_Init(HSE_CLK, RCC_CLK_72M);  // is a must due to MPU6050

	RCC_USART2_CLK_EN();
	TIMER1_Init(RCC_CLK_8M);
	Motor_Config_t DC_Motor1 =
	{
			.DC_Pin1Number = GPIO_PIN_4,
			.DC_Pin2Number = GPIO_PIN_5,
			.DC_PortNumber1 = GPIOA,
			.DC_PortNumber2 = GPIOA,
			.PWM_Timer = TIMER3,
			.PWM_Channel = TIMER_CH1
	};
	Motor_Config_t DC_Motor2 =
	{
			.DC_Pin1Number = GPIO_PIN_7,
			.DC_Pin2Number = GPIO_PIN_0,
			.DC_PortNumber1 = GPIOA,
			.DC_PortNumber2 = GPIOB,
			.PWM_Timer = TIMER3,
			.PWM_Channel = TIMER_CH4
	};


	GPIO_PinConfig_t StepperDirPin = {
			.GPIO_PinNumber = GPIO_PIN_8,
			.GPIO_MODE = GPIO_MODE_OUTPUT_PUSHPULL,
			.GPIO_OUTPUT_SPEED = GPIO_SPEED_2MHZ
	};

	UART_Config UART_Cfg;
	UART_Cfg.BaudRate = UART_BaudRate_115200;
	UART_Cfg.HWFlowCtrl = UART_HWFlowCtrl_NONE;
	UART_Cfg.IRQ_Enable = UART_IRQ_Enable_RXNE;
	UART_Cfg.P_IRQ_CallBack = UART_Test_Callback;
	UART_Cfg.Parity = UART_Parity_NONE;
	UART_Cfg.Payload_length = UART_Payload_Length_8B;
	UART_Cfg.StopBits = UART_StopBits_1;
	UART_Cfg.USART_Mode = UART_Mode_Tx_Rx;
	MCAL_UART_Init(USART2, &UART_Cfg);
	MCAL_UART_GPIO_SetPins(USART2);



	//RCC_GPIOC_CLK_EN();





	Motor_intialize(&DC_Motor1);

	Motor_intialize(&DC_Motor2);

	LCD_enuInit(&LCD_Configs);

	HC_SR04_Init(UltraSonic_Configs);
	Stepper_Init(&StepperDirPin);


	/* Loop forever */
	while (1) {



		if(newMessageArrived)
		{

			newMessageArrived = 0;


			if (RecievedFromServer == PARKING_REQUEST || RecievedFromServer == RETRIEVAL_REQUEST)
			{
				mySendChar = RECEIVED_OK;

				MCAL_UART_SendData(USART2, &mySendChar, Enable);
//				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

				// Check ultrasonics for arrival of the car

//				HC_SR04_ReadDistance(0,&Ultra1Distance);


				Ultra1Distance = 0;


				if(Ultra1Distance <= 5){
					mySendChar = CAR_ARRIVED;
					MCAL_UART_SendData(USART2, &mySendChar, Enable);
					MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

				}
			}
			if(RecievedFromServer == ACK_CAR_ARRIVED)
			{
				// Move to the Elevator, then send a "FIRST_REKEB"
				LCD_enuJumpCursorTo(1, 0);
				LCD_enuSendString("GOING_ToElevator");
				Motor_Move_ForWard(&DC_Motor1, 100);
				Motor_Move_ForWard(&DC_Motor2, 100);

				Delay_Timer1_ms(2000);

				Motor_TurnOff(&DC_Motor1);
				Motor_TurnOff(&DC_Motor2);

				Delay_Timer1_ms(3000);
				LCD_enuJumpCursorTo(1, 0);
				LCD_enuSendString("AT Elevator");
				mySendChar = FIRST_REKEB;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}else{
				mySendChar = RECEIVED_OK;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}


			if (RecievedFromServer == START_PARKING)
			{
				// Meaning that the 2d received a "FIRST_REKEB", and start Moving Procedures

				// Waiting for "ARRIVED_INFRONTOF_SLOT"

				mySendChar = ACK_STARTING;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);

				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);


				// Potentially not working

			}else{
				// Meaning that the 2nd didn't receive a "FIRST_REKEB"
				mySendChar = FIRST_REKEB;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}

			if(RecievedFromServer == ARRIVED_INFRONTOF_SLOT)
			{
				// Proceed with Parking procedures

				Proceed_Parking(&DC_Motor1, &DC_Motor2);
				mySendChar = DONE_PARKING;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);


			}else{
				mySendChar = ACK_STARTING;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);

				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}

			if(RecievedFromServer == ARRIVED_AT_ENTRY)
			{
				Delay_Timer1_ms(1000);
				Proceed_BackToHome(&DC_Motor1, &DC_Motor2);
				mySendChar = FIRST_HOME;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

			}else{
				mySendChar = DONE_PARKING;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

			}


			if(RecievedFromServer == FINISH_PARKING )
			{
				mySendChar = IM_DONE;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);

			}else{
				mySendChar = FIRST_HOME;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);
				MCAL_UART_ReceiveData(USART2, &RecievedFromServer, Enable);
			}



			if(RecievedFromServer == ACK_DONE)
			{
				LCD_enuJumpCursorTo(1, 0);
				LCD_enuSendString("AT HOME");
				RecievedFromServer = 0;

			}else{
				mySendChar = IM_DONE;
				MCAL_UART_SendData(USART2, &mySendChar, Enable);

			}


		}




	}



}





void Proceed_Parking(Motor_Config_t *Motor1, Motor_Config_t *Motor2)
{
	LCD_enuJumpCursorTo(1, 0);
	LCD_enuSendString("START");

	//HC_SR04_ReadDistance(0,&Ultra1Distance);
	//HC_SR04_ReadDistance(1,&Ultra2Distance);

	LCD_enuJumpCursorTo(1, 0);
	LCD_enuSendString("Reading ");

	LCD_enuJumpCursorTo(2, 0);
	LCD_enuSendString("1st:    ");
	LCD_enuJumpCursorTo(2, 5);
	LCD_enuDisplayIntNum(Ultra1Distance);

	LCD_enuJumpCursorTo(2, 9);
	LCD_enuSendString("2nd:    ");
	LCD_enuJumpCursorTo(2, 13);
	LCD_enuDisplayIntNum(Ultra2Distance);

	Motor_Move_ForWard(Motor1, 100);
	Motor_Move_ForWard(Motor2, 100);

	Delay_Timer1_ms(1000);

	Motor_TurnOff(Motor1);
	Motor_TurnOff(Motor2);

	Delay_Timer1_ms(500);

	if(Ultra2Distance<=2){
		// 8000 =~ 2cm
		// Move stepper up
		Stepper_Move_Steps(TIMER2, TIMER_CH1, 8000, 50, 500, Stepper_UP);

	}else if(Ultra2Distance>=4){ // 5
		// Move stepper down
		Stepper_Move_Steps(TIMER2, TIMER_CH1, 8000, 50, 500, Stepper_Down);

	} // 3
	else{

		// Calculate error
		error = TARGET_DISTANCE_MAX - Ultra2Distance;

		do{
			// Proportional term
			float P = Kp * error;

			// Integral term
			if (Ki != 0) {
				integral += error;
				if (integral > 100)
					integral = 100;
				else if (integral < -100)
					integral = -100;
			} else {
				integral = 0;
			}
			float I = Ki * integral;

			// Derivative term
			derivative = error - error_previous;
			float D = Kd * derivative;

			// Calculate PID output
			correction_steps = P + I + D;

			// Limit correction steps to avoid excessive adjustments
			if (correction_steps > 100) {
				correction_steps = 100;
			} else if (correction_steps < -100) {
				correction_steps = -100;
			}
			Stepper_Move_Steps(TIMER2, TIMER_CH1,(uint16_t)(1500 + correction_steps), 50, 500, Stepper_UP);
			// Update previous error for next iteration
			error_previous = error;

			//					Delay_Timer1_ms(1000);

			// re-read the distance
			HC_SR04_ReadDistance(1,&Ultra2Distance);
			LCD_enuJumpCursorTo(2, 9);
			LCD_enuSendString("2nd:    ");
			LCD_enuJumpCursorTo(2, 13);
			LCD_enuDisplayIntNum(Ultra2Distance);

			// re-Calculate error
			error = TARGET_DISTANCE_MAX - Ultra2Distance;

		}while(error);// control

	}

	Motor_Move_BackWard(Motor1, 100);
	Motor_Move_BackWard(Motor2, 100);

	Delay_Timer1_ms(1000);

	Motor_TurnOff(Motor1);
	Motor_TurnOff(Motor2);

	Delay_Timer1_ms(500);


}



void Proceed_BackToHome(Motor_Config_t *Motor1, Motor_Config_t *Motor2)
{
	Motor_Move_ForWard(Motor1, 100);
	Motor_Move_ForWard(Motor2, 100);

	Delay_Timer1_ms(1000);

	Motor_TurnOff(Motor1);
	Motor_TurnOff(Motor2);

	Delay_Timer1_ms(1000);
}















